# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory
WORKDIR /app

# Copy the rest of the application code
COPY . .

# Install dependencies
RUN pip install --upgrade pip && \
    pip install -r server/requirements.txt

ENV PYTHONPATH=/app

RUN ls -lah /app

EXPOSE 5000

# Command to run the application (change this as needed)
CMD ["python", "server/server.py"]